source 'https://rubygems.org'

ruby '2.2.3'

gem 'awesome_print'
gem 'dotenv'
gem 'rake'
gem 'sinatra'
gem 'rack-conneg'
gem 'actionpack', '~> 4'
gem 'i18n'
gem 'redis'
gem 'puma'
gem 'foreman'
gem 'curb', '~> 0.8'
gem 'connection_pool'

group :test do
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
  gem 'capybara'
  gem 'cucumber-api-steps', require: false #, github: 'theodi/cucumber-api-steps', branch: 'feature-test-content-type'
  gem 'coveralls'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'terminal-notifier-guard'
  gem 'rspec-pride'
  gem 'nokogiri'
end
